apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.sockshop-dev.104.154.98.225.xip.io
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop-dev.svc.cluster.local
